com::SeyedAliRoshan::www::CalendarTool
String com.SeyedAliRoshan.www.CalendarTool.iraniWeekDayStr[][]
String [] com.SeyedAliRoshan.www.CalendarTool.iraniMonthStr
int com.SeyedAliRoshan.www.CalendarTool.irYear
int com.SeyedAliRoshan.www.CalendarTool.irMonth
int com.SeyedAliRoshan.www.CalendarTool.irDay
int com.SeyedAliRoshan.www.CalendarTool.gYear
int com.SeyedAliRoshan.www.CalendarTool.gMonth
int com.SeyedAliRoshan.www.CalendarTool.gDay
int com.SeyedAliRoshan.www.CalendarTool.juYear
int com.SeyedAliRoshan.www.CalendarTool.juMonth
int com.SeyedAliRoshan.www.CalendarTool.juDay
int com.SeyedAliRoshan.www.CalendarTool.leap
int com.SeyedAliRoshan.www.CalendarTool.JDN
int com.SeyedAliRoshan.www.CalendarTool.march
com.SeyedAliRoshan.www.CalendarTool.CalendarTool()
JavaSource_Calendar: The default constructor uses the current Gregorian date to initialize the other private memebers of the class (Iranian and Julian dates).
References com.SeyedAliRoshan.www.CalendarTool.setGregorianDate.
com.SeyedAliRoshan.www.CalendarTool.CalendarTool(int year, int month, int day)
JavaSource_Calendar: This constructor receives a Gregorian date and initializes the other private members of the class accordingly. year int month int day int
References com.SeyedAliRoshan.www.CalendarTool.setGregorianDate.
int com.SeyedAliRoshan.www.CalendarTool.getIranianYear()
getIranianYear: Returns the 'year' part of the Iranian date.int
int com.SeyedAliRoshan.www.CalendarTool.getIranianMonth()
getIranianMonth: Returns the 'month' part of the Iranian date.int
Referenced by com.SeyedAliRoshan.www.CalendarTool.getIranianMonthStr.
int com.SeyedAliRoshan.www.CalendarTool.getIranianDay()
getIranianDay: Returns the 'day' part of the Iranian date.int
String com.SeyedAliRoshan.www.CalendarTool.getIranianWeekDayStr()
References com.SeyedAliRoshan.www.CalendarTool.getDayOfWeek.
String com.SeyedAliRoshan.www.CalendarTool.getIranianMonthStr()
References com.SeyedAliRoshan.www.CalendarTool.getIranianMonth.
int com.SeyedAliRoshan.www.CalendarTool.getGregorianYear()
getGregorianYear: Returns the 'year' part of the Gregorian date.int
int com.SeyedAliRoshan.www.CalendarTool.getGregorianMonth()
getGregorianMonth: Returns the 'month' part of the Gregorian date.int
int com.SeyedAliRoshan.www.CalendarTool.getGregorianDay()
getGregorianDay: Returns the 'day' part of the Gregorian date.int
int com.SeyedAliRoshan.www.CalendarTool.getJulianYear()
getJulianYear: Returns the 'year' part of the Julian date.int
int com.SeyedAliRoshan.www.CalendarTool.getJulianMonth()
getJulianMonth: Returns the 'month' part of the Julian date.int
int com.SeyedAliRoshan.www.CalendarTool.getJulianDay()
getJulianDay() Returns the 'day' part of the Julian date.int
String com.SeyedAliRoshan.www.CalendarTool.getIranianDate()
getIranianDate: Returns a string version of Iranian dateString
Referenced by com.SeyedAliRoshan.www.CalendarTool.toString.
String com.SeyedAliRoshan.www.CalendarTool.getIranianDate(String Pattern)
getIranianDate: Returns a string version of Iranian date with user pattern separator. Seyed Ali Roshan Pattern String
void com.SeyedAliRoshan.www.CalendarTool.setIranianDate(String jalaliAirDate)
String com.SeyedAliRoshan.www.CalendarTool.getGregorianDate()
getGregorianDate: Returns a string version of Gregorian dateString
Referenced by com.SeyedAliRoshan.www.CalendarTool.toString.
String com.SeyedAliRoshan.www.CalendarTool.getGregorianDate(String Pattern)
getGregorianDate: Returns a string version of Gregorian date which used user pattern as separator. Seyed Ali Roshan Pattern String
String com.SeyedAliRoshan.www.CalendarTool.getJulianDate()
getJulianDate: Returns a string version of Julian dateString
Referenced by com.SeyedAliRoshan.www.CalendarTool.toString.
String com.SeyedAliRoshan.www.CalendarTool.getWeekDayStr()
getWeekDayStr: Returns the week day name.String
References com.SeyedAliRoshan.www.CalendarTool.getDayOfWeek.
Referenced by com.SeyedAliRoshan.www.CalendarTool.toString.
String com.SeyedAliRoshan.www.CalendarTool.toString()
toString: Overrides the default toString() method to return all dates.String
References com.SeyedAliRoshan.www.CalendarTool.getWeekDayStr, com.SeyedAliRoshan.www.CalendarTool.getGregorianDate, com.SeyedAliRoshan.www.CalendarTool.getJulianDate, com.SeyedAliRoshan.www.CalendarTool.getIranianDate.
int com.SeyedAliRoshan.www.CalendarTool.getDayOfWeek()
getDayOfWeek: Returns the week day number. Monday=0..Sunday=6;int
Referenced by com.SeyedAliRoshan.www.CalendarTool.getIranianWeekDayStr, com.SeyedAliRoshan.www.CalendarTool.getWeekDayStr.
void com.SeyedAliRoshan.www.CalendarTool.nextDay()
nextDay: Go to next julian day number (JDN) and adjusts the other dates.
void com.SeyedAliRoshan.www.CalendarTool.nextDay(int days)
nextDay: Overload the nextDay() method to accept the number of days to go ahead and adjusts the other dates accordingly. days int
void com.SeyedAliRoshan.www.CalendarTool.previousDay()
previousDay: Go to previous julian day number (JDN) and adjusts the otehr dates.
void com.SeyedAliRoshan.www.CalendarTool.previousDay(int days)
previousDay: Overload the previousDay() method to accept the number of days to go backward and adjusts the other dates accordingly. days int
void com.SeyedAliRoshan.www.CalendarTool.setIranianDate(int year, int month, int day)
setIranianDate: Sets the date according to the Iranian calendar and adjusts the other dates. year int month int day int
void com.SeyedAliRoshan.www.CalendarTool.setGregorianDate(int year, int month, int day)
setGregorianDate: Sets the date according to the Gregorian calendar and adjusts the other dates. year int month int day int
Referenced by com.SeyedAliRoshan.www.CalendarTool.CalendarTool.
void com.SeyedAliRoshan.www.CalendarTool.setJulianDate(int year, int month, int day)
setJulianDate: Sets the date according to the Julian calendar and adjusts the other dates. year int month int day int
boolean com.SeyedAliRoshan.www.CalendarTool.IsLeap(int irYear1)
IsLeap: This method determines if the Iranian (Jalali) year is leap (366-day long) or is the common year (365 days), and finds the day in March (Gregorian Calendar)of the first day of the Iranian year ('irYear').Iranian year (irYear) ranges from (-61 to 3177).This method will set the following private data members as follows: leap: Number of years since the last leap year (0 to 4) Gy: Gregorian year of the begining of Iranian year march: The March day of Farvardin the 1st (first day of jaYear)
void com.SeyedAliRoshan.www.CalendarTool.IranianCalendar()
IranianCalendar: This method determines if the Iranian (Jalali) year is leap (366-day long) or is the common year (365 days), and finds the day in March (Gregorian Calendar)of the first day of the Iranian year ('irYear').Iranian year (irYear) ranges from (-61 to 3177).This method will set the following private data members as follows: leap: Number of years since the last leap year (0 to 4) Gy: Gregorian year of the begining of Iranian year march: The March day of Farvardin the 1st (first day of jaYear)
int com.SeyedAliRoshan.www.CalendarTool.IranianDateToJDN()
IranianDateToJDN: Converts a date of the Iranian calendar to the Julian Day Number. It first invokes the 'IranianCalender' private method to convert the Iranian date to Gregorian date and then returns the Julian Day Number based on the Gregorian date. The Iranian date is obtained from 'irYear'(1-3100),'irMonth'(1-12) and 'irDay'(1-29/31).long (Julian Day Number)
void com.SeyedAliRoshan.www.CalendarTool.JDNToIranian()
JDNToIranian: Converts the current value of 'JDN' Julian Day Number to a date in the Iranian calendar. The caller should make sure that the current value of 'JDN' is set correctly. This method first converts the JDN to Gregorian calendar and then to Iranian calendar.
int com.SeyedAliRoshan.www.CalendarTool.julianDateToJDN(int year, int month, int day)
julianDateToJDN: Calculates the julian day number (JDN) from Julian calendar dates. This integer number corresponds to the noon of the date (i.e. 12 hours of Universal Time). This method was tested to be good (valid) since 1 March, -100100 (of both calendars) up to a few millions (10^6) years into the future. The algorithm is based on D.A.Hatcher, Q.Jl.R.Astron.Soc. 25(1984), 53-55 slightly modified by K.M. Borkowski, Post.Astron. 25(1987), 275-279. year int month int day int int
void com.SeyedAliRoshan.www.CalendarTool.JDNToJulian()
JDNToJulian: Calculates Julian calendar dates from the julian day number (JDN) for the period since JDN=-34839655 (i.e. the year -100100 of both calendars) to some millions (10^6) years ahead of the present. The algorithm is based on D.A. Hatcher, Q.Jl.R.Astron.Soc. 25(1984), 53-55 slightly modified by K.M. Borkowski, Post.Astron. 25(1987), 275-279).
int com.SeyedAliRoshan.www.CalendarTool.gregorianDateToJDN(int year, int month, int day)
gergorianDateToJDN: Calculates the julian day number (JDN) from Gregorian calendar dates. This integer number corresponds to the noon of the date (i.e. 12 hours of Universal Time). This method was tested to be good (valid) since 1 March, -100100 (of both calendars) up to a few millions (10^6) years into the future. The algorithm is based on D.A.Hatcher, Q.Jl.R.Astron.Soc. 25(1984), 53-55 slightly modified by K.M. Borkowski, Post.Astron. 25(1987), 275-279. year int month int day int int
void com.SeyedAliRoshan.www.CalendarTool.JDNToGregorian()
JDNToGregorian: Calculates Gregorian calendar dates from the julian day number (JDN) for the period since JDN=-34839655 (i.e. the year -100100 of both calendars) to some millions (10^6) years ahead of the present. The algorithm is based on D.A. Hatcher, Q.Jl.R.Astron.Soc. 25(1984), 53-55 slightly modified by K.M. Borkowski, Post.Astron. 25(1987), 275-279).